Update README.md with Contributors Badges at the end
GlobeHoppin/globe-hoppin-backend pull request #20
Opened 2024-10-08 02:58 UTC by Muskan-bhatt249

2024-10-10 13:09 UTC, Mustafiz04 requested changes
Minor change

2024-10-10 13:09 UTC, Mustafiz04 commented on README.md
> +<a href="https://github.com/GlobeHoppin/globe-hoppin-backend/pulse">
```suggestion
<a href="https://github.com/GlobeHoppin/globe-hoppin-backend/graphs/contributors">
```

2024-10-10 14:08 UTC, Muskan-bhatt249 commented
@Mustafiz04 Changes done

2024-10-11 18:30 UTC, Mustafiz04 approved these changes

2024-10-11 18:36 UTC, merged